---
- name: Install packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  become: true

- name: Install font packages
  ansible.builtin.import_tasks: fonts.yml

- name: Install aur packages
  ansible.builtin.import_tasks: aur.yml
