---
- name: Install desktop environment
  when: desktop == "kde"
  block:
    - name: Install Plasma
      community.general.pacman:
        name:
          - plasma-meta
          - plasma-workspace
          - kde-graphics-meta
          - kde-multimedia-meta
          - kde-network-meta
          - kde-pim-meta
          - kde-sdk-meta
          - kde-system-meta
          - kde-utilities-meta
          - sddm
          - xdg-desktop-portal-kde
        state: present
      become: true
