---
- name: Zsh Shell Dependencies
  community.general.pacman:
    name:
      - zsh
      - fzf
      - zinit
      - fastfetch
    state: present
  become: true

- name: Zsh AUR Dependencies  
  kewlfft.aur.aur:
    name:
      - oh-my-posh-bin
    state: present
    use: "{{ aur_helper }}"
  become: true

- name: Change Shell
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ user.additional_groups }}"
    append: yes
    shell: "{{ user.shell }}"
    state: present
  become: true
