---
- name: Zsh Shell Dependencies
  community.general.pacman:
    name:
      - zsh
      - fzf
      - zinit
      - fastfetch
    state: present
  become: true

- name: Zsh AUR Dependencies  
  kewlfft.aur.aur:
    name:
      - oh-my-posh-bin
    state: present
    use: "{{ aur_helper }}"
  become: true
