---
- name: Install Xorg
  community.general.pacman:
    name:
      - xorg-xwayland
    state: present
  become: true

- name: Detect GPU
  ansible.builtin.shell: set -o pipefail && lspci -v | grep -A1 -e VGA -e 3D  # noqa command-instead-of-shell
  register: gpu_result
  changed_when: no

- name: Install GPU drivers (AMD)
  community.general.pacman:
    name:
      - mesa
      - mesa-vdpau
      - libva-mesa-driver
      - vulkan-radeon
      - xf86-video-amdgpu
      - rocm-hip-runtime
      - rocm-hip-sdk
      - hip-runtime-amd
      - rocm-core
      - rocm-opencl-runtime
      - rocm-opencl-sdk
    state: present
  become: true
  when: ("'Radeon' in gpu_result.stdout") or (("'AMD/ATI' in gpu_result.stdout"))

- name: Install GPU drivers (Intel)
  community.general.pacman:
    name:
      - mesa
      - intel-media-driver
      - libva-intel-driver
      - vulkan-intel
      - xf86-video-intel
    state: present
  become: true
  when: "'Intel' in gpu_result.stdout"
